---
title: 'quadagree: An R package for quadratically weighted agreement coefficients'
tags:
  - R
  - psychometrics
  - statistics
  - statistical inference
  - agreement
  - fleiss' kappa
  - cohen's kappa
  - brennan-prediger 
  - chance-corrected agreement
  - reliability
  - inter-rater reliability
authors:
  - name: Jonas Moss
  - orcid: 0000-0002-6876-6964
  - affiliation: "1"
  - corresponding: true
affiliations:
  - name: BI Business School, Norway
    index: 2
bibliography: paper.bib
date: 3 May 2023
---

# Summary

Chance-corrected measures of agreement are used to summarize the agreement among raters on a set of items. For instance, $6$ psychiatrists may rate psychiatric patients into one of the categories "depression", "personality disorder", "schizophrenia", or "neurosis" (Fleiss, 1971), and we may wish to quantify how much they agree with each other's ratings. There are several ways to compute chance-corrected agreement for such data, depending on how "chance agreement" is defined. Three popular options are Fleiss' kappa, Conger's kappa, and the Brennan-Prediger coefficient

Sometimes items are rated on an ordinal scale, e.g. a Likert scale from 1 -- 5. In such cases it is popular to measure disagreement using the quadratic distance function $(x-y)^2$. The chance-corrected agreement coefficients mentioned above can be defined for the quadratic distance as well. Then they may be called quadratically weighted agreement coefficients.

This package implements estimators and inferential methods for these coefficient. Details about the methods can be found in Moss and van Oest (2023) and Moss (2023). The main contribution of this package is consistent estimation and inference for the quadratic agreement coefficients with missing data, and, in addition, a method for calculating the novel kind of Brennan-Prediger coefficient introduced by Moss (2023).

# Statement of need
Agreement data with missing raters is common, but there are no methods available that estimates agreement coefficients for such data consistently. As a consequence, inferential methods such as confidence intervals will have arbitrarily bad coverage as $n$ increases. This package 


This package supports data on wide form and long form for Fleiss' kappa and the Brennan-Prediger coefficient, and long form for Cohen's kappa. In addition, if the data is on long form, estimation and inference with missing data and continuous is possible. Since inference with complete data is already possible using available packages such as `irrCAC`, we focus on missing data primarily. In addition, we support fast studentized bootstrap, 

Klein (2018) provides a data set of $5$ raters with some missing ratings. To calculate Fleiss' kappa for this data, call `fleissci`. The functions `bpci` and `cohenci` can be used to calculte the Brennan-Prediger coefficient and Cohen's kappa.

```{r}
library("quadagree")
fleissci(dat.klein2018)
```

Possible options for the `ci` functions include the `type` argument, where one may assume the ratings are elliptically or normally distributed for possibly improved performance. Moreover, setting `bootstrap = TRUE` runs a studentized bootstrap with `n_reps` repetitions. Since the studentized bootstrap is second-order consistent, one would expect it to have better coverage when $n$ is sufficiently large.

Our methods provide consistent estimators of the agreement coefficient, but existing packages such as `irrCAC` does not. The following provides and example.

# References
